const SearchActionTypes = {
    ADD_SEARCH: 'ADD_SEARCH',
    ADD_LAST_SEARCH: 'ADD_LAST_SEARCH',
    FETCH_LOCATION_START: 'FETCH_LOCATION_START',
    FETCH_LOCATION_SUCCESS: 'FETCH_LOCATION_SUCCESS',
    FETCH_LOCATION_FAILURE: 'FETCH_LOCATION_FAILURE'
}

export default SearchActionTypes;